### ISSUE TITLE
svtyper throws exception on cnvnator vcf

### ISSUE THREAD

**Issue by scalavision** [dnanexus/parliament2#37]
When running svtyper on `cnvnator.vcf` I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/svtyper", line 9, in <module>
    load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/usr/local/lib/python2.7/dist-packages/svtyper/classic.py", line 575, in cli
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/svtyper/classic.py", line 568, in main
    args.max_ci_dist)
  File "/usr/local/lib/python2.7/dist-packages/svtyper/classic.py", line 265, in sv_genotype
    ciA = confidence_interval(var, 'CIPOS', 'CIPOS95', max_ci_dist)
  File "/usr/local/lib/python2.7/dist-packages/svtyper/parsers.py", line 12, in confidence_interval
    ci = map(int, var.info[tag].split(','))
KeyError: 'CIPOS'
```
Looking at this line and by investigating the python scripts being used, it seems like it should be the `cvnator.ci.vcf` file that should be the target of svtyper?

https://github.com/dnanexus/parliament2/blob/master/parliament2.sh#L471

The keys `CIPOS` and `CIEND` and several others are needed by svtyper and are not available in the original `cnvnator.vcf` file.

**Comment by slzarate** [comment]
Thank you for reporting this issue! I will look into this.
