### ISSUE TITLE
problem running on CentOS Linux

### ISSUE THREAD

**Issue by sgivan** [dnanexus/parliament2#39]
I am having problems getting Parliament2 running in a Docker container on CentOS. I'll spare you the longer story. If I spin up a vanilla CentOS 7.4 VM on AWS, install docker, pull down dnanexus/Parliament2:0.1.9 and run it with this command:

`sudo docker run -v /mnt/bucket00/projects/cnv/input/:/home/dnanexus/in -v /mnt/bucket00/projects/cnv/output/:/home/dnanexus/out dnanexus/parliament2:0.1.9 --bam test.bam --bai test.bam.bai --fai genome.fa.fai -r genome.fa --breakdancer --manta --cnvnator --genotype`

I get this output:

Set up and index BAM/CRAM
BAM file input, index exists
mv: cannot move '/home/dnanexus/in/test.bam' to '/home/dnanexus/in/input.bam': Permission denied
mv: cannot move '/home/dnanexus/in/test.bam.bai' to '/home/dnanexus/in/input.bam.bai': Permission denied
touch: cannot touch '/home/dnanexus/in/test.bam': Permission denied
touch: cannot touch '/home/dnanexus/in/done.txt': Permission denied
Generate contigs
[E::hts_open_format] Failed to open file input.bam
samtools view: failed to open "input.bam" for reading: No such file or directory
mkdir: cannot create directory '/home/dnanexus/out/log_files/': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
Launching jobs that cannot be parallelized by contig
Manta
parliament2.sh: line 167: /home/dnanexus/out/log_files/manta_logs/test.manta.stdout.log: No such file or directory
Processing bam input.bam
open: No such file or directory
Failed to open samfile input.bam
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
Launching jobs parallelized by contig
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/log_files': Permission denied
mkdir: cannot create directory '/home/dnanexus/out/sv_caller_results/': Permission denied
Converting results to VCF format
Convert Manta results to VCF format
No outputs of Manta found. Continuing.
Traceback (most recent call last):
  File "/miniconda/bin/pip", line 4, in <module>
    import pip
  File "/miniconda/lib/python2.7/site-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/miniconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
    @_call_aside
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
    f(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3143, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 633, in _build_master
    ws = cls()
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__
    self.add_entry(entry)
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File "/miniconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2110, in find_on_path
    for entry in os.listdir(path_item):
OSError: [Errno 13] Permission denied: '/miniconda/bin'
ERROR: SVTyper requested, but candidate VCF files required to genotype. No VCF files found.
Traceback (most recent call last):
  File "/home/dnanexus/parliament2.py", line 80, in <module>
    main()
  File "/home/dnanexus/parliament2.py", line 76, in main
    run_parliament(args.bam, args.bai, ref_genome_name, args.fai, prefix, args.filter_short_contigs, args.breakdancer, args.breakseq, args.manta, args.cnvnator, args.lumpy, args.delly_deletion, args.delly_insertion, args.delly_inversion, args.delly_duplication, args.genotype, args.svviz, args.svviz_only_validated_candidates, args.dnanexus)
  File "/home/dnanexus/parliament2.py", line 49, in run_parliament
    subprocess.check_call(['bash', 'parliament2.sh', bam, bai, ref_genome, fai, prefix, str(filter_short_contigs), str(breakdancer), str(breakseq), str(manta), str(cnvnator), str(lumpy), str(delly_deletion), str(delly_insertion), str(delly_inversion), str(delly_duplication), str(genotype), str(svviz), str(svviz_only_validated_candidates), str(dnanexus)])
  File "/miniconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'parliament2.sh', '/home/dnanexus/in/test.bam', '/home/dnanexus/in/test.bam.bai', '/home/dnanexus/in/genome.fa', '/home/dnanexus/in/genome.fa.fai', 'test', 'False', 'True', 'False', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'False']' returned non-zero exit status 1

As you can see, the errors start with:

mv: cannot move '/home/dnanexus/in/test.bam' to '/home/dnanexus/in/input.bam': Permission denied
mv: cannot move '/home/dnanexus/in/test.bam.bai' to '/home/dnanexus/in/input.bam.bai': Permission denied

I think the inability to create the input.bam and input.bam.bai  files leads to all the subsequent errors. I've tried this on two other CentOS machines and generated similar errors. The /mnt/bucket00/projects/cnv/input and /mnt/bucket00/projects/cnv/output directories are 0777, so they should be writable by anyone.

**However**, if I run the exact same command on an AWS Ubuntu 18 LTS VM it runs to completion with no unexpected errors. Has anyone else seen this behavior? Is there an easy fix without forking and heavily customizing the code? 

Thanks.

**Comment by slzarate** [comment]
I have not tested this on a CentOS machine, unfortunately. This may be a naive attempt at a fix, but could you try using `sudo docker run`?

Otherwise, the Docker container is using Ubuntu 14.04, so I would look into running Ubuntu Docker containers on CentOS machines in general.

**Comment by sgivan** [comment]
Thanks for answering. I got this working by **not** installing the system version of docker and following the directions on this page to install a more recent version: https://linuxize.com/post/how-to-install-and-use-docker-on-centos-7/ .
